version: 0.0
os: linux

files:
  - source: /
    destination: /var/app/current/
    
  - source: scripts/
    destination: /var/app/current/scripts/

permissions:
  - object: /var/app/current/
    owner: webapp
    group: webapp
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh  # Remove absolute path
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh  # Remove absolute path
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_application.sh  # Remove absolute path
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_application.sh  # Remove absolute path
      timeout: 300
      runas: root
