version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React application..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed. Uploading artifacts to S3..."

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no
  name: react-build-$(date +%Y-%m-%d).zip
