version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust this to match your Node.js version
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: build  # Ensuring only the build folder is deployed
