version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g serve   # Ensure "serve" is installed globally
  build:
    commands:
      - echo Building the React app...
      - npm run build
      - echo Packaging application...
      - zip -r deploy.zip build/ Procfile package.json package-lock.json
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - deploy.zip
  discard-paths: yes
