version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Adjust if needed
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building React app..."
      - npm run build
  post_build:
    commands:
      - echo "Zipping build files..."
      - cd build && zip -r ../deploy.zip .
      - cd ..
      - echo "Uploading to S3..."
      - aws s3 cp deploy.zip s3://react-app-artifacts-21-02-2025/deploy.zip
      - echo "Creating a new Beanstalk application version..."
      - aws elasticbeanstalk create-application-version \
          --application-name TravelAd-Frontend \
          --version-label build-$(date +%Y%m%d%H%M%S) \
          --source-bundle S3Bucket="react-app-artifacts-21-02-2025",S3Key="deploy.zip"
      - echo "Updating Beanstalk environment with new version..."
      - aws elasticbeanstalk update-environment \
          --environment-name TravelAd-Frontend-env \
          --version-label build-$(date +%Y%m%d%H%M%S)

artifacts:
  files:
    - deploy.zip
