version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - zip -r build.zip * # Archive the build output
      - aws s3 cp build.zip s3://react-app-artifacts-21-02-2025/build.zip

artifacts:
  files:
    - '**/*'
